modLoader = "javafml" #mandatory
loaderVersion = "[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "GNU Lesser General Public License v3.0" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "mvs" #mandatory
version = "${version}-forge" #mandatory
displayName = "Moog's Voyager Structures" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Thanks to my Olver, the main builder as well as TelepathicGrunt for their structure mod template and rs" #optional
authors = "FinnDog" #optional
description = '''80+ structures made with vanilla blocks and entities bringing life to your world!
Discover loot, enemies, & villagers along the way!

Join our community here: https://discord.gg/S5nffJbuvA
''' #mandatory (Supports multiline text)
[[dependencies.mes]] #optional
modId="forge"
mandatory=true
versionRange="[41,)"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.mes]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"
