modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/FinnSetchell/MoogsVoyagerStructures/issues" #optional
license="https://github.com/FinnSetchell/MoogsVoyagerStructures/blob/1.20-MultiLoader/LICENSE"

[[mods]]
    modId="mvs"
    logoFile= "assets/mvs/icon.png"
    logoBlur=false
    version="${version}"
    displayName="Moog's Voyager Structures"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures"
    authors="FinnDog"
    credits="Thanks to Olver, the main builder as well as TelepathicGrunt for their structure mod template and rs"
    description='''
    Moogs Voyager Structures brings life, fun and variety to your Minecraft world!
    Explore awesome new structures made with vanilla blocks and entities, and discover loot,
    enemies, and villagers along the way. This mod is compatible with any modpack and keeps
    the vanilla feel of the game!
    '''

[[mixins]]
    config = "mvs-neoforge.mixins.json"

[[mixins]]
    config = "mvs-common.mixins.json"

[[dependencies.mvs]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"